# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 020066cbfa1f36fa30cc5ddf01f93f11f117bda1db9a69f22afb85a83b79c5a0288db59daf885082915f89314ba8a16f680033f0481c29ec94e946655dfb9b41

test:
  secret_key_base: 6d950297308e08df92514e2d93f523e556bce21c21ebb58b5a32f8435a1277a7569109c0ce7886f0d92ab68daf7bf55f166a2bada3e7530a73b2b34465479fbb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
